name: Run Virtual Machine with QEMU

on:
  workflow_dispatch:

jobs:
  run-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-system-x86

      - name: Download QCOW2 file
        run: wget https://github.com/cctv-security/Win10/raw/main/Windows10.qcow2 -O Windows10.qcow2

      - name: Run Virtual Machine with VNC
        run: |
          qemu-system-x86_64 \
          -hda Windows10.qcow2 \
          -m 4G \
          -enable-kvm \
          -vga std \
          -display vnc=127.0.0.1:0 \
          -cpu host -smp 2
