name: Run Telegram Bot

on:
  push:
    branches:
      - main  # تغيير هذا إلى الفرع الذي ترغب في تشغيل الـ Workflow عليه
  workflow_dispatch:  # يتيح تشغيل الـ Workflow يدويًا من واجهة GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # اختر الإصدار الذي ترغب به (مثلًا '16')

    - name: Install dependencies
      run: |
        npm install  # يقوم بتثبيت جميع الحزم المطلوبة

    - name: Start Telegram Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # سر البوت الخاص بك
        ADMIN_ID: ${{ secrets.ADMIN_ID }}    # ID الخاص بالمسؤول
        API_KEY: ${{ secrets.API_KEY }}      # مفتاح الـ API الخاص بك
      run: |
        node index.mjs  # قم بتعديل الاسم إذا قمت بتغيير اسم الملف إلى index.mjs
